site_name: Avaliação de Qualidade

theme:
  name: material
  language: pt-BR
  palette:
    # Modo Claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo Escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy

nav:
  - Início: index.md
  - Fase 1: fase1/index.md
  - Fase 2:
      - Segurança: fase2/index.md
      - Confiabilidade: fase2/confiabilidade.md
  - Fase 3:
    - Segurança: fase3/seguranca.md
    - Confiabilidade: fase3/confiabilidade.md
  - Fase 4:
    - Segurança: fase4/seguranca.md
    - Confiabilidade: fase4/confiabilidade.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js